### ISSUE TITLE
Failed to interpret file as a pickle

### ISSUE THREAD

**Issue by cnlinxi** [alokprasad/LPCTron#8]
I run script 'training.sh' in Tacotron-2 but synthesized npy files cannot be read, the error is like: Failed to interpret file 'xxx/audio-LJ047-0098.npy' as a pickle.
Anyone incomes this error? Thanks

**Comment by carlfm01** [comment]
Hello @cnlinxi  Are you using `np.fromfile `and not `np.load`?

**Comment by cnlinxi** [comment]
> Hello @cnlinxi Are you using `np.fromfile `and not `np.load`?

Yes, I should use `np.fromfile` instead of `np.load`.
Thanks a lot :)
